print("Iniciando mi aprendizaje en Python.")
print("En el mundo de la programación")
print("---------------------------------------------")
print("Python el lenguaje de la IA")
print()
print("Soluciones inteligentes para problemas complejos")
print()
print("---------------------------------------------")
print("Aprendiendo sobre el cambio\nde línea en Python")
print()
print("Será de mucha\nutillidad el uso dentro de líneas")
print()
print("---------------------------------------------")
# print("\")  # produce error
print("\\")  # no produce error
print()
print("---------------------------------------------")
print("Python mi", "lenguaje", "preferido en este 2026.")
print()
print("---------------------------------------------")
print("Mi nombre es", "Python.")
print("Monty Python.")
