print("Mi nombre es", "Python.", end=" ")
print("Monty Python.")
print()
print("--------------------------------------")
print("Mi nombre es ", end="")
print("Monty Python")
print()
print("--------------------------------------")
print("Fresa", "Naranja", "Mandarina", end=" ")
print( "Uva", "Sandia")
print()
print("Deseamos unir dos líneas en una ", end=",")
print("y veremos que se vuelven una sola")
print()
print("El resultado es:", end=" ---> ")
print("50")
print()
print("Saludar", end=" ")
print("a todos", end="!")
print()
print("10", end=" ")
print("Es la edad de ese joven")
print()
print("Podemos usar end para", end="\n")
print("cambios de línea")
print()
print("Podemos delimitar el espaciado así", end="     ")
print("el espacio será el de end entre las líneas")
print()
print("end= la veremos de gran utilidad cuando veamos ciclos repetitivos")
