print("Estoy", "aprendiendo", "el", "uso", "de", "separador", sep="-")
print()
print("Otro ejemplo de uso","de sep en mi script", sep=" ")
print()
print("1,2,3", sep="-")
print()
print(*"Bienvenidos", sep="\n")
print("* Hace un recorrido en nuestra cadena, solo tomar nota por el momento")
print("Luego tendremos más uso con dicha instrucción")
print()
print("Podemos usar sep=","con el espacio o contenido","que necesitemos", sep="   ")
print()
print("a","b","c","d", sep=",")
print()
print("Veremos el uso de sep en ciclos repetitivos y despliegue de resultados muy útil")
